services:
  ms-user:
    image: postgres
    container_name: ms-user-db
    environment:
      - POSTGRES_PASSWORD=pg1234
      - POSTGRES_USERNAME=postgres
      - POSTGRES_DB=ms-user-db
    ports:
      - 5432:5432

  ms-email:
    image: postgres
    container_name: ms-email-db
    environment:
      - POSTGRES_PASSWORD=pg1234
      - POSTGRES_USERNAME=postgres
      - POSTGRES_DB=ms-email-db
    ports:
      - 5433:5432    
